include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true  # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: false  # Uncomment to enable the `prefer_single_quotes` rule
    always_use_package_imports: true  # DONT USE this format in imports import '../lib/baz.dart';
    avoid_relative_lib_imports: true  # DONT USE this format in imports import '../lib/baz.dart';
    avoid_empty_else: true
    avoid_returning_null_for_future: true # It is almost always wrong to return null for a Future. Most of the time the developer simply forgot to put an async keyword on the function.
    avoid_type_to_string: true # # DONT USE if (other.runtimeType.toString() == 'Bar') { doThing();} Ok=> if (other is Bar) {doThing();.
    avoid_types_as_parameter_names: true # DONT USE m(f(int));  Ok=> m(f(int v));
    cancel_subscriptions: true # StreamSubscription _subscriptionA.
    close_sinks: true # _sinkB = File(filename).openWrite(); // OK.
    collection_methods_unrelated_type: true # DONT USE (list.contains('1')) print('someFunction'); set.remove('1'); Ok=> if (list.contains(1)) print('someFunction');
    comment_references: true # DONT USE Return true if [value] is larger than [outOfScopeId]. Ok=> /// Return the larger of [a] or [b].
    control_flow_in_finally: true # DONT USE Return true if [value] is larger than [outOfScopeId]. Ok=> /// Return the larger of [a] or [b].
    discarded_futures: true # DON'T invoke asynchronous functions in non-async blocks.
    literal_only_boolean_expressions: true # There must be a real condition.
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_relative_imports: false # DONT USE this format in imports import '../lib/baz.dart';
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    use_key_in_widget_constructors: true
    camel_case_types: true
    empty_catches: true
    always_put_control_body_on_new_line: true
    empty_constructor_bodies: true
    file_names: true # DONT USE file names SliderMenu.dart  Ok=> slider_menu.dart
