name: news_feeds_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  # Flutter SDK and packages
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  photo_view: ^0.14.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.9
  cached_network_image: ^3.2.3
  connectivity_plus:
  flutter_native_splash: ^2.2.17
  lottie: ^2.2.0
  intl:
  webview_flutter: ^4.2.1







dev_dependencies:
  # Libraries for development/testing
  json_serializable:
  build_test:
  convert:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# Configure splash screen
flutter_native_splash:
  image: "assets/splash/splash.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  background_image: "assets/splash/background.jpeg"

  # android 12
  android_12:
    color: "#2437AC"
    color_dark: "#2437AC"
    icon_background_color: "#2437AC"
    icon_background_color_dark: "#2437AC"
    image: assets/splash/splash.png
    image_android: assets/splash/splash.png
    image_dark: assets/splash/splash.png
    image_ios": assets/splash/splash.png
    fullscreen: true

  fullscreen: true

flutter:
  # Use material design
  uses-material-design: true

  # Define asset folders and files
  assets:
    - assets/splash/
    - assets/icons/
    - assets/gif/
    - assets/translations/
    - assets/app_setting_json.json
